import Link from 'next/link';
import Image from 'next/image';

interface HeroProps {
    headline?: string;
    subheading?: string;
}

export default function Hero({
    headline = "Fresh Bread Baked Daily",
    subheading = "Premium artisan bakery with 5+ years of tradition. Handcrafted with love in Zululand."
}: HeroProps) {
    return (
        <section className="relative h-screen md:h-96 w-full overflow-hidden">
            {/* Hero Background Image (Generated by Nano) */}
            <Image
                src="/images/hero-banner.jpg"
                alt="Fresh Sharo Bakery bread"
                fill
                className="object-cover"
                priority
                sizes="100vw"
                quality={90}
            />

            {/* Dark overlay for text readability */}
            <div className="absolute inset-0 bg-black/40"></div>

            {/* Text Content Overlay */}
            <div className="relative z-10 flex items-center justify-start h-full px-4 md:px-16 lg:px-24">
                <div className="max-w-2xl">
                    <h1 className="text-4xl md:text-6xl font-bold text-white mb-4 leading-tight">
                        {headline}
                    </h1>
                    <p className="text-lg md:text-xl text-gray-100 mb-8">
                        {subheading}
                    </p>
                    <div className="flex gap-4">
                        <Link
                            href="/products"
                            className="inline-block bg-sharo-gold text-sharo-brown px-8 py-3 font-bold rounded-lg hover:opacity-90 transition"
                        >
                            View Products
                        </Link>
                        <Link
                            href="/about"
                            className="inline-block border-2 border-white text-white px-8 py-3 font-bold rounded-lg hover:bg-white hover:text-sharo-brown transition"
                        >
                            Learn More
                        </Link>
                    </div>
                </div>
            </div>
        </section>
    );
}
